/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressDto {
  city?: string;
  county?: string;
  houseNumber?: number;
  id?: number;
  street?: string;
  userId?: number;
  zipCode?: number;
}
