/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionDto {
  amount?: number;
  destinationIban?: string;
  id?: number;
  transactionDate?: string;
  type?: 'TRANSFERT' | 'DEPOSIT';
  userId?: number;
}
